## YAML Template.
kafka:
  message:
    max:
      size: "1000000"
  bootstrapServer: ""
  bootstrapServerPort: ""
  retrieval: 
    groupConfig: ""
  #ssl:
    #cert: ""
    #passcode: ""
  topic:
    names: "newtopic"
  consumer: 
    enable: "true"
  auto:
    commit: "false"
        
    
        
    
